### ISSUE TITLE
Can't compile currently

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/hpoannotqc#1]
On my mac `mvn clean package` fails with:

`[ERROR] Failed to execute goal on project HpoAnnotQC: Could not resolve dependencies for project monarchinitiative:HpoAnnotQC:jar:0.1.12: Could not find artifact com.github.phenomics:ontolib-io:jar:0.1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

Do I have to install ontolib locally?

**Comment by pnrobinson** [comment]
sorry, yes ontolib/OLPG fork needs to be installed via mvn install

**Comment by pnrobinson** [comment]
closing this. Please reopen if there is an issue. Note we have switched from OLPG to the new phenol version.
