### ISSUE TITLE
Problem with gene/phenotype link files complementary to phenotype.hpoa data

### ISSUE THREAD

**Issue by seoanezonjic** [monarch-initiative/hpoannotqc#55]
Hi 
In https://hpo.jax.org/app/data/annotations we can download the hpoa file from http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa and also the gene/phenotype files:
- http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt 
- http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt

Focusing in genes_to_phenotype.txt file, the format a year ago was:
```
#Format: entrez-gene-id<tab>entrez-gene-symbol<tab>HPO-Term-ID<tab>HPO-Term-Name<tab>Frequency-Raw<tab>Frequency-HPO<tab>Additional Info from G-D source<tab>G-D source<tab>disease-ID for link
8192    CLPP    HP:0000815      Hypergonadotropic hypogonadism  -               -       mim2gene        OMIM:614129
8192    CLPP    HP:0000013      Hypoplasia of the uterus        -               -       mim2gene        OMIM:614129
8192    CLPP    HP:0000252      Microcephaly    -       HP:0040283      -       mim2gene        OMIM:614129
8192    CLPP    HP:0000007      Autosomal recessive inheritance -               -       mim2gene        OMIM:614129
```
Now is:
```
ncbi_gene_id    gene_symbol     hpo_id  hpo_name
10      NAT2    HP:0000007      Autosomal recessive inheritance
10      NAT2    HP:0001939      Abnormality of metabolism/homeostasis
16      AARS1   HP:0002460      Distal muscle weakness
16      AARS1   HP:0002451      Limb dystonia
16      AARS1   HP:0010871      Sensory ataxia
```
I cannot find information about this change neither how to retrieve the gene-hpo-disease given previously by genes_to_phenotype.txt file. Do you know about this?
Thank you in advance
Pedro Seoane

**Comment by iimpulse** [comment]
Hi @seoanezonjic,

We are aware and the columns were intentionally dropped for now (there are assumptions made). In the next release we will have gene-2-disease and the mapping will have to be done manually based on these 2 files.

**Comment by seoanezonjic** [comment]
Hi @iimpulse 
Thank you by your answer. Which is the reason to drop these columns? And, what criteria is used to generate the current files and the future gene-2-disease files?

**Comment by iimpulse** [comment]
This repository is quite stale and likely needs a rewrite. But essentially, we wanted to make these files more succinct. Some of the columns dropped such as frequency was really the frequency of phenotype to disease, but was also then implied on on hpo-gene. Moving forward we wanted to it to be clear that these are all inherited from the relationship. It's been quite some time so I'm going to close this. If you have any questions or needs please open a new ticket! Thanks.
