### ISSUE TITLE
Small File Changes

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/hpoannotqc#62]
Small file format changes have broken downstream hpoa generation due to bioformat. We need to create a pipeline to insure that this does not happen in the future.

**Comment by pnrobinson** [comment]
We should have the HpoAnnotationFileParser crash if there is a parse error. At this stage of the project, we need to demand that all input files have a correct format.

**Comment by pnrobinson** [comment]
Implemented, the app now crashes and also outputs a file with a list of things that need to be fixed.

**Comment by iimpulse** [comment]
>.> committing to master? Shame on you.
