### ISSUE TITLE
add code to replace double semicolons with a single semicolon in the v2 files.

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/hpoannotqc#7]
In disease name entries like this
```
 CONGENITAL DISORDER OF GLYCOSYLATION, TYPE IIn; CDG2N;;CDG IIn; CDGIIn
```
see #6

**Comment by cmungall** [comment]
I wouldn't spend too much time on this as you'll have sensible names 
from MONDO soon

**Comment by pnrobinson** [comment]
I'll miss the caps, somehow :-0


Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by pnrobinson** [comment]
I am closing this issue as we will not correct this for now.
